import type { Tool, Category } from '@/types';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'writing',
    name: 'Writing',
    slug: 'writing',
    description:
      'AI writing assistants, grammar checkers, content generators, and copywriting tools.',
    icon: '✍️',
  },
  {
    id: 'image',
    name: 'Image Generation',
    slug: 'image-generation',
    description: 'AI image generators, art creators, photo editors, and visual design tools.',
    icon: '🎨',
  },
  {
    id: 'video',
    name: 'Video & Audio',
    slug: 'video-audio',
    description: 'AI video editors, text-to-video generators, audio tools, and podcast assistants.',
    icon: '🎬',
  },
  {
    id: 'code',
    name: 'Code & Dev Tools',
    slug: 'code-dev-tools',
    description:
      'AI coding assistants, code completion, debugging, and developer productivity tools.',
    icon: '💻',
  },
  {
    id: 'productivity',
    name: 'Productivity',
    slug: 'productivity',
    description: 'AI productivity tools, meeting assistants, note-taking, and workflow automation.',
    icon: '⚡',
  },
];

const now = new Date().toISOString();

export const SEED_TOOLS: Tool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    slug: 'chatgpt',
    tagline: 'Conversational AI assistant for writing, coding, analysis and more.',
    description:
      'ChatGPT by OpenAI is a general-purpose conversational AI that can draft essays, write code, answer questions, summarize documents, and brainstorm ideas. It supports GPT-4 and GPT-4o models with vision, file upload, and browsing capabilities.',
    categories: ['writing', 'code', 'productivity'],
    tags: ['chatbot', 'gpt-4', 'openai', 'writing', 'code'],
    features: [
      'Text generation',
      'Code generation',
      'Image understanding',
      'File analysis',
      'Web browsing',
      'Plugin ecosystem',
    ],
    pricing: {
      free: true,
      tiers: [
        { name: 'Plus', price: '$20/mo', features: ['GPT-4o', 'DALL·E', 'Advanced Data Analysis'] },
      ],
    },
    website: 'https://chat.openai.com',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/chatgpt', url: '/placeholders/chatgpt.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/chatgpt-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.7, count: 1280 },
    reviewCount: 342,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 45200, clicks: 12400, installs: 8900 },
    featured: true,
    editorialScore: 95,
    pros: ['Extremely versatile', 'Large plugin ecosystem', 'Supports vision and file uploads'],
    cons: ['Free tier has usage limits', 'Can hallucinate facts', 'Requires internet connection'],
    bestFor: 'General-purpose AI tasks, writing, and coding',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    slug: 'midjourney',
    tagline: 'Create stunning AI-generated art and images from text prompts.',
    description:
      'Midjourney is a leading AI image generation tool that creates photorealistic and artistic images from text descriptions. Known for its exceptional aesthetic quality, it operates through Discord and a dedicated web interface.',
    categories: ['image'],
    tags: ['image-generation', 'art', 'design', 'creative'],
    features: ['Text-to-image', 'Style variations', 'Upscaling', 'Remix mode', 'Pan & zoom'],
    pricing: {
      free: false,
      tiers: [
        { name: 'Basic', price: '$10/mo', features: ['200 images/mo'] },
        { name: 'Standard', price: '$30/mo', features: ['Unlimited relaxed'] },
      ],
    },
    website: 'https://midjourney.com',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/midjourney', url: '/placeholders/midjourney.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/midjourney-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.8, count: 980 },
    reviewCount: 278,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 38500, clicks: 10200, installs: 7100 },
    featured: true,
    editorialScore: 93,
    pros: ['Best-in-class image quality', 'Active community', 'Constantly improving models'],
    cons: ['No free tier', 'Discord-only for some features', 'Steep learning curve for prompts'],
    bestFor: 'Artists, designers, and creative professionals',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    tagline: 'AI pair programmer that helps you write code faster.',
    description:
      'GitHub Copilot is an AI-powered code completion tool that suggests whole lines or blocks of code as you type. Built on OpenAI Codex, it supports dozens of languages and integrates into VS Code, JetBrains, and Neovim.',
    categories: ['code'],
    tags: ['code-completion', 'developer', 'github', 'ide'],
    features: [
      'Inline code suggestions',
      'Chat interface',
      'Multi-file context',
      'Test generation',
      'Documentation',
    ],
    pricing: {
      free: false,
      tiers: [
        { name: 'Individual', price: '$10/mo', features: ['Unlimited completions'] },
        {
          name: 'Business',
          price: '$19/user/mo',
          features: ['Admin controls', 'Policy management'],
        },
      ],
    },
    website: 'https://github.com/features/copilot',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/github-copilot', url: '/placeholders/copilot.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/copilot-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.6, count: 890 },
    reviewCount: 215,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 32100, clicks: 8900, installs: 6200 },
    featured: true,
    editorialScore: 92,
    pros: ['Seamless IDE integration', 'Excellent for boilerplate', 'Supports many languages'],
    cons: [
      'Paid only',
      'Sometimes suggests incorrect code',
      'Privacy concerns with code sent to cloud',
    ],
    bestFor: 'Professional developers and teams',
  },
  {
    id: 'jasper',
    name: 'Jasper',
    slug: 'jasper',
    tagline: 'AI copywriting and content marketing platform for teams.',
    description:
      'Jasper is an AI content platform designed for marketing teams. It helps create blog posts, ad copy, social media content, and product descriptions using customizable brand voice and templates.',
    categories: ['writing'],
    tags: ['copywriting', 'marketing', 'content', 'seo'],
    features: [
      'Brand voice',
      '50+ templates',
      'SEO mode',
      'Chrome extension',
      'Team collaboration',
    ],
    pricing: {
      free: false,
      tiers: [
        { name: 'Creator', price: '$49/mo', features: ['1 brand voice', 'SEO mode'] },
        { name: 'Pro', price: '$69/mo', features: ['3 brand voices', 'Art generation'] },
      ],
    },
    website: 'https://jasper.ai',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/jasper', url: '/placeholders/jasper.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/jasper-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.4, count: 620 },
    reviewCount: 189,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 22400, clicks: 6100, installs: 3800 },
    featured: false,
    editorialScore: 85,
    pros: ['Great for marketing teams', 'Strong template library', 'Brand voice consistency'],
    cons: [
      'Expensive for individuals',
      'Quality varies by template',
      'Learning curve for advanced features',
    ],
    bestFor: 'Marketing teams and content creators',
  },
  {
    id: 'runway',
    name: 'Runway',
    slug: 'runway',
    tagline: 'AI-powered creative suite for video generation and editing.',
    description:
      'Runway is a next-generation creative suite offering AI-powered video editing, generation, and visual effects. Its Gen-2 model can generate video from text or images, while offering tools like background removal, motion tracking, and inpainting.',
    categories: ['video'],
    tags: ['video-generation', 'editing', 'creative', 'vfx'],
    features: [
      'Text-to-video (Gen-2)',
      'Background removal',
      'Motion tracking',
      'Inpainting',
      'Green screen',
    ],
    pricing: {
      free: true,
      tiers: [
        { name: 'Standard', price: '$12/mo', features: ['625 credits/mo'] },
        { name: 'Pro', price: '$28/mo', features: ['2250 credits/mo'] },
      ],
    },
    website: 'https://runwayml.com',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/runway', url: '/placeholders/runway.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/runway-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.5, count: 540 },
    reviewCount: 156,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 28700, clicks: 7800, installs: 4500 },
    featured: true,
    editorialScore: 90,
    pros: [
      'Industry-leading video generation',
      'Comprehensive editing suite',
      'Free tier available',
    ],
    cons: ['Credits run out fast', 'Video length limited', 'Rendering can be slow'],
    bestFor: 'Video creators and filmmakers',
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    slug: 'notion-ai',
    tagline: 'AI writing and knowledge management built into Notion.',
    description:
      'Notion AI brings artificial intelligence directly into the Notion workspace. It can summarize pages, generate content, extract action items, translate text, and answer questions about your workspace documents.',
    categories: ['productivity', 'writing'],
    tags: ['notes', 'workspace', 'knowledge-management', 'writing'],
    features: [
      'Summarization',
      'Content generation',
      'Action items',
      'Translation',
      'Q&A over docs',
    ],
    pricing: {
      free: false,
      tiers: [
        {
          name: 'AI Add-on',
          price: '$10/member/mo',
          features: ['Unlimited AI usage', 'All AI features'],
        },
      ],
    },
    website: 'https://notion.so/product/ai',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/notion-ai', url: '/placeholders/notion.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/notion-ai-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.3, count: 470 },
    reviewCount: 132,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 19800, clicks: 5400, installs: 3200 },
    featured: false,
    editorialScore: 82,
    pros: ['Seamless Notion integration', 'Works with your existing docs', 'Easy to use'],
    cons: ['Requires Notion subscription', 'AI quality inconsistent', 'Limited customization'],
    bestFor: 'Notion users who want AI-powered productivity',
  },
  {
    id: 'descript',
    name: 'Descript',
    slug: 'descript',
    tagline: 'AI-powered video and podcast editing as easy as editing a doc.',
    description:
      'Descript is an all-in-one audio and video editor that lets you edit media by editing text. It features AI-powered transcription, filler word removal, eye contact correction, Studio Sound, and screen recording.',
    categories: ['video'],
    tags: ['podcast', 'video-editing', 'transcription', 'audio'],
    features: [
      'Edit by transcript',
      'Filler word removal',
      'Screen recording',
      'AI voices',
      'Studio Sound',
    ],
    pricing: {
      free: true,
      tiers: [
        { name: 'Hobbyist', price: '$24/mo', features: ['10 hrs transcription'] },
        { name: 'Pro', price: '$33/mo', features: ['30 hrs transcription'] },
      ],
    },
    website: 'https://descript.com',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/descript', url: '/placeholders/descript.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/descript-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.5, count: 380 },
    reviewCount: 105,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 16500, clicks: 4200, installs: 2800 },
    featured: false,
    editorialScore: 84,
    pros: [
      'Revolutionary text-based editing',
      'Great for podcasters',
      'Multiple AI features included',
    ],
    cons: [
      'Steep learning curve',
      'Performance issues with large files',
      'Transcription not always accurate',
    ],
    bestFor: 'Podcasters and video content creators',
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    slug: 'grammarly',
    tagline: 'AI writing assistant for grammar, clarity, and tone.',
    description:
      'Grammarly is the most popular AI writing assistant, offering real-time grammar, spelling, punctuation, and style suggestions. Its generative AI features help rewrite, summarize, and compose text across browsers, desktop, and mobile apps.',
    categories: ['writing'],
    tags: ['grammar', 'writing-assistant', 'proofreading', 'tone'],
    features: [
      'Grammar check',
      'Tone detection',
      'Plagiarism check',
      'Generative AI',
      'Browser extension',
    ],
    pricing: {
      free: true,
      tiers: [
        { name: 'Premium', price: '$12/mo', features: ['Full writing feedback', 'Plagiarism'] },
        { name: 'Business', price: '$15/member/mo', features: ['Brand tones', 'Analytics'] },
      ],
    },
    website: 'https://grammarly.com',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/grammarly', url: '/placeholders/grammarly.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/grammarly-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.6, count: 1540 },
    reviewCount: 420,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 52300, clicks: 14100, installs: 11200 },
    featured: true,
    editorialScore: 91,
    pros: [
      'Works everywhere via extensions',
      'Free tier is solid',
      'Excellent grammar and style suggestions',
    ],
    cons: [
      'Premium is pricey for students',
      'Suggestions can be overly cautious',
      'Generative AI is new and basic',
    ],
    bestFor: 'Students, professionals, and non-native English speakers',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    slug: 'cursor',
    tagline: 'AI-first code editor built for pair programming with AI.',
    description:
      'Cursor is a fork of VS Code rebuilt around AI. It features AI chat, multi-file editing via natural language, intelligent autocomplete with context-aware suggestions, and the ability to reference documentation and codebases in conversations.',
    categories: ['code'],
    tags: ['ide', 'code-editor', 'ai-coding', 'developer'],
    features: [
      'AI chat in editor',
      'Multi-file AI edits',
      'Codebase-aware context',
      'Auto-complete',
      'Doc references',
    ],
    pricing: {
      free: true,
      tiers: [
        { name: 'Pro', price: '$20/mo', features: ['Unlimited completions', '500 fast requests'] },
        {
          name: 'Business',
          price: '$40/user/mo',
          features: ['Admin controls', 'Centralized billing'],
        },
      ],
    },
    website: 'https://cursor.com',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/cursor', url: '/placeholders/cursor.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/cursor-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.7, count: 620 },
    reviewCount: 187,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 29400, clicks: 8100, installs: 5600 },
    featured: true,
    editorialScore: 94,
    pros: [
      'Native AI integration feels seamless',
      'Multi-file context awareness',
      'Fast and responsive',
    ],
    cons: [
      'VS Code fork may lack some extensions',
      'Expensive for individuals',
      'Learning AI prompting takes time',
    ],
    bestFor: 'Developers who want deep AI integration in their editor',
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    slug: 'otter-ai',
    tagline: 'AI meeting assistant for transcription, notes, and action items.',
    description:
      'Otter.ai is an AI-powered meeting assistant that provides real-time transcription, automated meeting summaries, action items, and searchable meeting notes. It integrates with Zoom, Google Meet, and Microsoft Teams.',
    categories: ['productivity'],
    tags: ['transcription', 'meeting', 'notes', 'collaboration'],
    features: [
      'Real-time transcription',
      'Meeting summaries',
      'Action items',
      'Speaker ID',
      'Zoom/Teams/Meet integration',
    ],
    pricing: {
      free: true,
      tiers: [
        { name: 'Pro', price: '$16.99/mo', features: ['90 min/conversation', 'Advanced search'] },
        { name: 'Business', price: '$30/user/mo', features: ['6000 min/mo', 'Admin controls'] },
      ],
    },
    website: 'https://otter.ai',
    affiliateUrl: '',
    logos: { publicId: 'bestapp/logos/otter-ai', url: '/placeholders/otter.svg' },
    screenshots: [
      { publicId: 'bestapp/screenshots/otter-ai-1', url: '/placeholders/screenshot.svg' },
    ],
    rating: { avg: 4.4, count: 410 },
    reviewCount: 124,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
    metrics: { views: 18200, clicks: 4900, installs: 3100 },
    featured: false,
    editorialScore: 83,
    pros: [
      'Excellent real-time transcription',
      'Great meeting integrations',
      'Free tier is generous',
    ],
    cons: ['Accuracy drops with accents', 'Limited offline capabilities', 'UI can be cluttered'],
    bestFor: 'Professionals with frequent meetings',
  },
];
